services:
  - type: worker
    name: bestdeb-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BESTDEBRID_API_KEY
        sync: false
      - key: AUTHORIZED_USERS
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: API_TIMEOUT
        value: "1"
    
